# Generated by Django 5.1.7 on 2025-04-05 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Name or idea for the tool', max_length=150)),
                ('description', models.TextField(help_text='Describe what the tool should do, its features, etc.')),
                ('requester_email', models.EmailField(blank=True, help_text="(Optional) Provide your email if you'd like an update.", max_length=254, null=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tool Request',
                'verbose_name_plural': 'Tool Requests',
                'ordering': ['-requested_date'],
            },
        ),
    ]
